name: inbox-zero-services
services:
  redis:
    image: redis
    ports:
      - ${REDIS_PORT:-6380}:6379
    volumes:
      - database-data:/data
    networks:
      - inbox-zero-network

  serverless-redis-http:
    ports:
      - "${REDIS_HTTP_PORT:-8079}:80"
    image: hiett/serverless-redis-http:latest
    env_file:
      - ./apps/web/.env
    environment:
      SRH_MODE: env
      SRH_TOKEN: ${UPSTASH_REDIS_TOKEN}
      SRH_CONNECTION_STRING: "redis://redis:6379" # Using `redis` hostname since they're in the same Docker network.
    networks:
      - inbox-zero-network

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    env_file:
      - ./.env
    depends_on:
      - redis
    ports:
      - ${WEB_PORT:-3000}:3000
    networks:
      - inbox-zero-network
    environment:
      DIRECT_URL: "${DATABASE_URL}"

volumes:
  database-data:

networks:
  inbox-zero-network:
